# Generated by Django 5.2.4 on 2025-07-21 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_split_status_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='split',
            name='expense',
        ),
        migrations.AddField(
            model_name='split',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.group'),
            preserve_default=False,
        ),
    ]
